name: Build and Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore SentinelPro.sln

      - name: Build Solution
        run: dotnet build SentinelPro.sln --configuration Release --no-restore

      - name: Publish Artifacts
        run: dotnet publish SentinelPro.sln -c Release -o wwwroot/publish --no-build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SentinelPro-Setup
          path: wwwroot/publish/
